name: "Terraform Infrastructure CI/CD"
on:
 push:
   branches:
   - main

jobs:
 terraform:
   name: "Terraform Infrastructure"
   runs-on: ubuntu-latest
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
     - name: Terraform ci
       uses: hashicorp/setup-terraform@v3

     - name: Terraform fmt
       run: terraform fmt -check
       continue-on-error: true 
     - name: Terraform init
       env:
          AWS_ACCESS_KEY_ID: ${{ secrets. AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY_ID }}
       run: terraform init

     - name: Terraform plan
       env:
          AWS_ACCESS_KEY_ID: ${{ secrets. AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY_ID }}  
       run: terraform plan
        