name: terraform validate
on: 
    push:
        branches:
            - main
jobs:
    fmt:
        runs-on: ubantu-latest
        name: running terraform format
        steps:
            - name: git check out
              uses: actions/checkout@v4

            - name: terraform fmt
              uses: dflook/terraform-fmt@v2
        